-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- 华夏神话 schema + seed (public-domain《山海经》data).

DROP TABLE IF EXISTS creatures;
DROP TABLE IF EXISTS graph_nodes;
DROP TABLE IF EXISTS graph_links;

CREATE TABLE creatures (
  ord INTEGER NOT NULL,
  id TEXT PRIMARY KEY,
  glyph TEXT NOT NULL, cat TEXT NOT NULL, region TEXT NOT NULL,
  omen TEXT NOT NULL, color TEXT NOT NULL,
  zh TEXT NOT NULL, en TEXT NOT NULL, py TEXT NOT NULL,
  tags_zh TEXT NOT NULL, tags_en TEXT NOT NULL,
  src TEXT NOT NULL, ref TEXT NOT NULL, bai TEXT NOT NULL, en_sum TEXT NOT NULL
);
CREATE INDEX idx_creatures_cat ON creatures(cat);
CREATE INDEX idx_creatures_region ON creatures(region);
CREATE INDEX idx_creatures_omen ON creatures(omen);

CREATE TABLE graph_nodes (
  ord INTEGER NOT NULL,
  id TEXT PRIMARY KEY,
  zh TEXT NOT NULL, en TEXT NOT NULL, g TEXT NOT NULL,
  r INTEGER NOT NULL, desc_zh TEXT NOT NULL, desc_en TEXT NOT NULL
);
CREATE TABLE graph_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  s TEXT NOT NULL, t TEXT NOT NULL, r TEXT NOT NULL
);

INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (0,'jiuweihu','狐','yi','nan','xiong','#c83f33','九尾狐','Nine-Tailed Fox','Jiǔwěihú','["食人","能避蛊"]','["Devours men","Wards off poison"]','青丘之山，有兽焉，其状如狐而九尾，其音如婴儿，能食人，食者不蛊。','《南山经》','青丘山中有兽形如狐而生九条尾巴，叫声如婴儿啼哭，能吃人；食其肉者可不受蛊毒之害。后世渐演为祥瑞与魅惑的双面象征。','A nine-tailed fox of Green Hills whose cry mimics an infant. It devours people, yet eating its flesh wards off poison — later remembered as both omen of peace and seductress.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (1,'luzhu','鹿','xiang','nan','ji','#c9a24a','鹿蜀','Lushu','Lùshǔ','["佩之宜子孙"]','["Blesses offspring"]','杻阳之山，有兽焉，其状如马而白首，其文如虎而赤尾，其音如谣，其名曰鹿蜀，佩之宜子孙。','《南山经》','杻阳山上的鹿蜀，形如白头之马，身有虎纹、赤色尾巴，鸣声似人吟唱；佩戴其皮毛可使子孙兴旺。','A horse-bodied beast with a white head, tiger-stripes and a crimson tail whose call is like a chant. Wearing its hide is said to bless one''s descendants.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (2,'fenghuang','凤','niao','nan','ji','#c9a24a','凤皇','Fenghuang','Fènghuáng','["见则天下安宁","五采"]','["Brings peace","Five-hued"]','丹穴之山，有鸟焉，其状如鸡，五采而文，名曰凤皇……是鸟也，饮食自然，自歌自舞，见则天下安宁。','《南山经》','丹穴山的凤皇形如鸡而羽备五彩，头纹为德、翼纹为义、背纹为礼、膺纹为仁、腹纹为信；自饮自食、自歌自舞，一现身则天下太平。','The five-colored phoenix of Cinnabar Cave whose markings spell virtue, duty, ritual, benevolence and trust. It eats and dances of its own accord; its appearance heralds peace under heaven.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (3,'bofang','毕','niao','xi','xiong','#2f6f7a','毕方','Bifang','Bìfāng','["一足","主怪火"]','["One-legged","Omen of fire"]','章莪之山，有鸟焉，其状如鹤，一足，赤文青质而白喙，名曰毕方，其鸣自叫也，见则其邑有讹火。','《西山经》','章莪山的毕方形如鹤却只有一足，青身赤纹、白喙；鸣声呼其自名，所到之处常有无端怪火。','A one-legged crane-like bird, blue-bodied with red markings and a white beak. It calls its own name, and where it appears, uncanny fires break out.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (4,'qiongqi','穷','xiong_b','xi','xiong','#c83f33','穷奇','Qiongqi','Qióngqí','["食人","四凶之一"]','["Devours men","One of Four Fiends"]','邽山，有兽焉，其状如牛，猬毛，名曰穷奇，音如獆狗，是食人。','《西山经》','邽山的穷奇状如牛而披刺猬般硬毛，吼声如狗嗥，专以食人。后列为''四凶''，传其助恶抑善。','An ox-shaped beast bristling with hedgehog spines, howling like a dog and feeding on men. Counted among the Four Fiends, it was said to reward the wicked.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (5,'didiang','帝','shen','xi','zhong','#7a3b54','帝江','Dijiang','Dìjiāng','["无面目","识歌舞","浑沌"]','["Faceless","Knows song & dance"]','天山，有神焉，其状如黄囊，赤如丹火，六足四翼，浑敦无面目，是识歌舞，实为帝江也。','《西山经》','天山之神帝江，形如黄色口袋，红如丹火，六足四翼，浑然一团而无面目，却通晓歌舞——即''浑沌''之原型。','A deity like a yellow sack glowing fire-red, with six legs and four wings, faceless yet versed in song and dance — the very origin of Chaos (Hundun).');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (6,'taowu','檮','xiong_b','xi','xiong','#c83f33','梼杌','Taowu','Táowù','["四凶之一","顽凶难训"]','["One of Four Fiends","Untamable"]','状如虎，毛长二尺，人面虎足，猪口牙，尾长一丈八尺，号难训。','《神异经》','梼杌形如虎而毛长二尺，人面虎足、猪口獠牙、尾长丈八，顽愚凶恶、傲狠不可教训，为''四凶''之一。','A tiger-formed fiend with a man''s face, boar''s tusks and an eighteen-foot tail. Stubborn and savage beyond all teaching, it is one of the Four Fiends.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (7,'taotie','饕','xiong_b','bei','xiong','#c83f33','狍鸮 · 饕餮','Taotie','Tāotiè','["贪食","目在腋下"]','["Insatiable","Eyes in armpits"]','钩吾之山，有兽焉，其状如羊身人面，其目在腋下，虎齿人爪，其音如婴儿，名曰狍鸮，是食人。','《北山经》','钩吾山的狍鸮，羊身人面、目在腋下、虎齿人爪，叫声似婴啼而食人——即青铜器上贪食无厌的''饕餮''。','A sheep-bodied man-faced beast with eyes under its arms, tiger fangs and human claws, crying like an infant as it devours men — the gluttonous Taotie of bronze ritual vessels.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (8,'jingwei','精','niao','bei','ji','#2f6f7a','精卫','Jingwei','Jīngwèi','["衔石填海","炎帝之女"]','["Fills the sea","Daughter of Yandi"]','发鸠之山，有鸟焉，其状如乌，文首、白喙、赤足，名曰精卫……是炎帝之少女，名曰女娃，游于东海，溺而不返，故为精卫，常衔西山之木石，以堙于东海。','《北山经》','炎帝幼女女娃溺于东海，化为精卫鸟——形如乌鸦，花首白喙赤足，日衔西山木石填东海，誓不与海休止，成坚毅不屈之象征。','Yandi''s drowned daughter reborn as a bird with a patterned head, white beak and red feet. Forever she carries twigs and stones to fill the East Sea — an emblem of unyielding will.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (9,'dangkang','当','xiang','dong','ji','#c9a24a','当康','Dangkang','Dāngkāng','["见则大穰","丰年之兆"]','["Sign of harvest"]','钦山，有兽焉，其状如豚而有牙，其名曰当康，其鸣自叫，见则天下大穰。','《东山经》','钦山的当康形如长牙之猪，鸣声呼唤自名；它一出现，便预示天下五谷丰登的大丰之年。','A tusked, boar-like beast of Qin Mountain that calls its own name. Wherever it appears, a year of great harvest is foretold.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (10,'zhulong','烛','shen','haiwai','zhong','#c9a24a','烛龙 · 烛阴','Zhulong','Zhúlóng','["视为昼瞑为夜","身长千里"]','["Eyes make day & night"]','钟山之神，名曰烛阴，视为昼，瞑为夜，吹为冬，呼为夏，不饮，不食，不息，息为风，身长千里……人面，蛇身，赤色。','《海外北经》','钟山之神烛龙，人面蛇身、赤色，身长千里；睁眼为白昼、闭眼成黑夜，吹气是寒冬、呼气为盛夏，其呼吸即化作风。','A thousand-li serpent-deity with a human face and crimson body. Opening its eyes brings day, closing them night; its breath turns to winter, summer and the winds.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (11,'yinglong','应','shen','dahuang','ji','#2f6f7a','应龙','Yinglong','Yìnglóng','["有翼之龙","杀蚩尤夸父"]','["Winged dragon","Slew Chiyou"]','大荒东北隅中，有山名曰凶犁土丘。应龙处南极，杀蚩尤与夸父，不得复上，故下数旱。','《大荒东经》','应龙为有翼之龙，曾助黄帝斩杀蚩尤与夸父，力竭不能复升于天，故所居之地常苦干旱；亦传其以尾画地成江河。','The winged dragon who slew Chiyou and Kuafu for the Yellow Emperor. Spent, it could not return to heaven, and the land below it suffers drought; some say its tail carved the rivers.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (12,'xiangliu','相','xiong_b','haiwai','xiong','#c83f33','相柳','Xiangliu','Xiāngliǔ','["九首","共工之臣"]','["Nine heads","Gonggong''s vassal"]','共工之臣曰相柳氏，九首，以食于九山。相柳之所抵，厥为泽溪。……禹厥之，三仞三沮，乃以为众帝之台。','《海外北经》','共工之臣相柳，九头人面蛇身，食于九山；所触之处尽成沼泽毒水。大禹杀之，其血腥臭难平，遂以其地筑众帝之台。','Gonggong''s nine-headed serpent minister who fed on nine mountains and poisoned all it touched into marsh. Yu slew it, and on the cursed ground raised a terrace of the gods.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (13,'xingtian','刑','shen','haiwai','ji','#c83f33','刑天','Xingtian','Xíngtiān','["断首犹战","以乳为目"]','["Headless warrior"]','刑天与帝至此争神，帝断其首，葬之常羊之山，乃以乳为目，以脐为口，操干戚以舞。','《海外西经》','刑天与天帝争位，被断其首，葬于常羊山；遂以双乳为目、肚脐为口，左持盾右执斧，舞动不止——百折不挠之魂。','A titan who warred with the High God and was beheaded. Burying his skull, he made nipples his eyes and navel his mouth, and dances on with shield and axe — defiance that death cannot end.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (14,'jingwei2','开','shen','hainei','zhong','#c9a24a','开明兽','Kaiming','Kāimíng','["九首人面","守昆仑"]','["Nine human heads","Guards Kunlun"]','昆仑南渊深三百仞。开明兽身大类虎而九首，皆人面，东向立昆仑上。','《海内西经》','昆仑之丘的守护神兽开明，身形如虎而生九首，皆为人面，向东而立，镇守天帝下都之门。','Guardian of Kunlun, the earthly capital of the High God: tiger-bodied with nine human faces, it stands facing east upon the sacred mountain.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (15,'luwu','陆','shen','xi','zhong','#7a3b54','陆吾','Luwu','Lùwú','["虎身九尾","司天之九部"]','["Tiger body, nine tails"]','昆仑之丘，是实惟帝之下都，神陆吾司之。其神状虎身而九尾，人面而虎爪，是神也，司天之九部及帝之囿时。','《西山经》','陆吾为昆仑之丘的主神，虎身九尾、人面虎爪，执掌天界的九部疆域与天帝苑囿的时序。','Lord-spirit of Kunlun: a tiger''s body with nine tails, a human face and tiger claws. He governs the nine quarters of heaven and the seasons of the god''s garden.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (16,'yingzhao','英','shen','xi','ji','#2f6f7a','英招','Yingzhao','Yīngzhāo','["马身人面","虎纹鸟翼"]','["Horse body, bird wings"]','槐江之山……神英招司之，其状马身而人面，虎文而鸟翼，徇于四海，其音如榴。','《西山经》','槐江山之神英招，马身人面、身具虎纹、背生鸟翼，巡行四海传天帝之命，鸣声如辘轳抽水之响。','Warden-spirit of Mount Huaijiang: a horse''s body, human face, tiger-stripes and bird''s wings. He patrols the four seas bearing the god''s word, his voice like a turning well-pulley.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (17,'qinyuan','钦','yi','xi','xiong','#c83f33','钦原','Qinyuan','Qīnyuán','["如蜂之毒","蠚兽则死"]','["Lethal sting"]','昆仑之丘，有鸟焉，其状如蜂，大如鸳鸯，名曰钦原，蠚鸟兽则死，蠚木则枯。','《西山经》','昆仑之丘的钦原，形如蜂而大若鸳鸯；蜇刺鸟兽则毙命，蜇刺草木则枯死，毒烈无比。','A bee-shaped creature of Kunlun, large as a mandarin duck. Its sting kills any bird or beast and withers any tree it touches.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (18,'huashe','化','yi','zhong','xiong','#2f6f7a','化蛇','Huashe','Huàshé','["人面豺身","见则大水"]','["Omen of flood"]','阳水出焉……其中多化蛇，其状如人面而豺身，鸟翼而蛇行，其音如叱呼，见则其邑大水。','《中山经》','阳水多化蛇，人面豺身、生鸟翼而如蛇爬行，叫声似人厉声呵斥；它一出现，城邑便遭大水之灾。','A creature of the Yang River with a human face, jackal''s body and bird''s wings that crawls like a snake. Its harsh cry foretells a great flood.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (19,'mafu','马','xiong_b','zhong','xiong','#c83f33','马腹','Mafu','Mǎfù','["人面虎身","食人"]','["Man-eater"]','蔓渠之山，伊水出焉……有兽焉，其名曰马腹，其状如人面虎身，其音如婴儿，是食人。','《中山经》','蔓渠山伊水之畔有马腹，人面虎身，鸣声似婴儿啼哭以诱人，实则凶猛食人。','A beast of Mount Manqu by the Yi River: human-faced, tiger-bodied, crying like an infant to lure prey before it devours them.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (20,'fuzhu','夫','yi','zhong','xiong','#2f6f7a','夫诸','Fuzhu','Fūzhū','["白鹿四角","见则大水"]','["Four-horned deer","Omen of flood"]','敖岸之山……有兽焉，其状如白鹿而四角，名曰夫诸，见则其邑大水。','《中山经》','敖岸山的夫诸，状如白鹿却生四角，温顺却为不祥之兆——它一现身，城邑必遭水患。','A white-deer-like beast of Mount Aoan crowned with four horns. Gentle in form yet ill in omen: its appearance brings flood to the town.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (21,'helo','何','lin','bei','ji','#2f6f7a','何罗鱼','Heluo Fish','Héluóyú','["一首十身","食之已痈"]','["One head, ten bodies","Cures sores"]','谯明之山，谯水出焉……其中多何罗之鱼，一首而十身，其音如吠犬，食之已痈。','《北山经》','谯水多何罗鱼，一个头却连着十个身子，叫声如犬吠；食其肉可治痈疮肿毒。','A fish of the Qiao River with one head and ten bodies, barking like a dog. Eating it is said to cure abscesses and swellings.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (22,'feiyi','肥','lin','xi','xiong','#c9a24a','肥遗','Feiyi','Féiyí','["六足四翼","见则大旱"]','["Omen of drought"]','太华之山……有蛇焉，名曰肥遗，六足四翼，见则天下大旱。','《西山经》','太华山的肥遗，是一条六足四翼的奇蛇；它一出现，天下便陷入大旱之灾。','A serpent of Mount Taihua bearing six legs and four wings. Its appearance heralds a great drought across the land.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (23,'xuangui','旋','lin','nan','ji','#2f6f7a','旋龟','Xuangui','Xuánguī','["鸟首虺尾","佩之不聋"]','["Cures deafness"]','怪水出焉……其中多旋龟，其状如龟而鸟首虺尾，其名曰旋龟，其音如判木，佩之不聋，可以为底。','《南山经》','怪水中多旋龟，形如龟却生鸟头蛇尾，声如劈木；佩戴它可使人耳聪不聋，还能治足茧。','A turtle of the Guai River with a bird''s head and serpent''s tail, sounding like splitting wood. Worn as a charm it keeps the ears from going deaf.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (24,'lu','鯥','lin','nan','ji','#c9a24a','鯥','Lu Fish','Lù','["冬死夏生","食之无肿疾"]','["Dies in winter, lives in summer"]','有鱼焉，其状如牛，陵居，蛇尾有翼，其羽在魼下，其音如留牛，其名曰鯥，冬死而夏生，食之无肿疾。','《南山经》','鯥形如牛却栖居陆地，蛇尾生翼、翼在胁下，叫声如犁牛；冬伏如死、夏复苏生，食之可免肿病。','An ox-shaped fish that dwells on land, with a winged serpent''s tail. It seems to die in winter and revives in summer; eating it prevents swellings.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (25,'boyi','猼','xiang','nan','ji','#c9a24a','猼訑','Boyi','Bóyí','["九尾四耳","佩之不畏"]','["Banishes fear"]','基山……有兽焉，其状如羊，九尾四耳，其目在背，其名曰猼訑，佩之不畏。','《南山经》','基山的猼訑，形如羊而有九尾四耳，眼睛长在背上；佩其皮毛能令人无所畏惧。','A sheep-like beast of Mount Ji with nine tails, four ears and eyes set in its back. To wear its hide is to know no fear.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (26,'gudiao','蛊','xiong_b','nan','xiong','#c83f33','蛊雕','Gudiao','Gǔdiāo','["有角","婴儿之音"]','["Horned","Cries like a baby"]','鹿吴之山……泽更之水出焉……其中多蛊雕，其状如雕而有角，其音如婴儿之音，是食人。','《南山经》','泽更之水多蛊雕，状如雕鹰却头生独角，叫声似婴儿啼以诱人，实为食人之凶兽。','An eagle-like beast of the Zegeng River bearing a single horn, crying like an infant to lure victims it then devours.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (27,'zheng','狰','yi','xi','xiong','#c83f33','狰','Zheng','Zhēng','["赤豹五尾","声如击石"]','["Red leopard, five tails"]','章莪之山……有兽焉，其状如赤豹，五尾一角，其音如击石，其名曰狰。','《西山经》','章莪山的狰，形如赤色之豹，生五条尾、头长一角，吼声如击石铿锵。','A beast of Mount Zhang''e shaped like a red leopard, with five tails and one horn, its roar ringing like struck stone.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (28,'huan','讙','xiang','xi','ji','#2f6f7a','讙','Huan','Huān','["一目三尾","可御凶"]','["Wards off evil"]','翼望之山……有兽焉，其状如狸，一目而三尾，名曰讙，其音如夺百声，是可以御凶，服之已瘅。','《西山经》','翼望山的讙，状如野猫却独眼三尾，能发百种声响；养之可抵御凶邪，食之能治黄疸之疾。','A wildcat-like beast of Mount Yiwang with a single eye and three tails, able to mimic a hundred voices. It wards off evil and cures jaundice.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (29,'yong','颙','niao','nan','xiong','#c9a24a','颙','Yong','Yóng','["人面四目","见则大旱"]','["Omen of drought"]','令丘之山……有鸟焉，其状如枭，人面四目而有耳，其名曰颙，其鸣自号也，见则天下大旱。','《南山经》','令丘山的颙，形如猫头鹰却生人面、四目而有耳，鸣声呼唤自名；它一出现，天下便陷大旱。','An owl-like bird of Mount Lingqiu with a human face, four eyes and ears. It calls its own name, and its appearance brings great drought.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (30,'tulou','土','xiong_b','xi','xiong','#c83f33','土蝼','Tulou','Tǔlóu','["四角","食人"]','["Four horns","Man-eater"]','昆仑之丘……有兽焉，其状如羊而四角，名曰土蝼，是食人。','《西山经》','昆仑之丘的土蝼，状如羊却生四只利角，性凶猛而食人。','A sheep-shaped beast of Kunlun armed with four horns — fierce, and a devourer of men.');
INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (31,'baize','白','xiang','dahuang','ji','#c9a24a','白泽','Baize','Báizé','["通万物之情","知鬼神"]','["Knows all spirits"]','帝乃问之天下鬼神之事，自古精气为物、游魂为变者凡万物之数，皆描而记之，作《白泽图》。','《轩辕本纪》','白泽为通晓万物之情的祥瑞神兽，能言人语、辨尽天下鬼神精怪。黄帝东巡遇之，问尽鬼神之事，乃成《白泽图》以备万物。','An auspicious sage-beast that speaks and knows the nature of every spirit and demon. From its counsel the Yellow Emperor compiled the legendary Baize Chart of ten thousand beings.');

INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (0,'pangu','盘古','Pangu','chuangshi',34,'开天辟地，垂死化生万物。','Split chaos into heaven and earth; his dying body became the world.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (1,'nuwa','女娲','Nüwa','chuangshi',30,'抟土造人，炼石补天。','Shaped humans from clay and mended the broken sky with five-colored stones.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (2,'fuxi','伏羲','Fuxi','sanhuang',30,'始作八卦，教民渔猎。','Devised the Eight Trigrams and taught fishing and hunting.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (3,'yandi','炎帝 · 神农','Yandi · Shennong','sanhuang',28,'尝百草，兴农耕医药。','Tasted the hundred herbs; father of farming and medicine.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (4,'huangdi','黄帝','Yellow Emperor','sanhuang',32,'人文初祖，败蚩尤定天下。','Ancestor of civilization; defeated Chiyou to unite the realm.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (5,'chiyou','蚩尤','Chiyou','xiongshen',28,'兵主战神，铜头铁额，败于涿鹿。','God of war with a bronze head; fell at the Battle of Zhuolu.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (6,'kuafu','夸父','Kuafu','yingxiong',24,'逐日而渴死，弃杖化邓林。','Chased the sun, died of thirst; his staff became a peach forest.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (7,'gonggong','共工','Gonggong','xiongshen',26,'怒触不周山，天柱折。','Smashed Mount Buzhou in rage, toppling a pillar of heaven.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (8,'zhurong','祝融','Zhurong','shen',24,'火神，与共工大战。','God of fire who warred against Gonggong.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (9,'zhuanxu','颛顼','Zhuanxu','wudi',26,'绝地天通，黄帝之孙。','Severed the path between heaven and earth; grandson of Huangdi.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (10,'diku','帝喾','Diku','wudi',24,'五帝之一，尧之父。','One of the Five Emperors, father of Yao.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (11,'yao','尧','Yao','wudi',26,'禅让于舜，命羿射日。','Abdicated to Shun; sent Yi to shoot the suns.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (12,'shun','舜','Shun','wudi',26,'孝感动天，受尧禅让。','Famed for filial virtue; received the throne from Yao.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (13,'gun','鲧','Gun','yingxiong',22,'窃息壤治水，败而化黄龙。','Stole the swelling-soil to quell the flood; failed and became a yellow dragon.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (14,'dayu','大禹','Yu the Great','yingxiong',30,'疏川治水，三过家门不入。','Tamed the great flood by dredging rivers; passed his home thrice without entering.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (15,'houyi','后羿','Houyi','yingxiong',28,'射落九日，得不死之药。','Shot down nine of ten suns; won the elixir of immortality.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (16,'change','嫦娥','Chang''e','yingxiong',26,'窃药奔月，化为月神。','Swallowed the elixir and flew to the moon.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (17,'xiwangmu','西王母','Xiwangmu','shen',28,'掌不死之药与刑罚的昆仑女神。','Queen Mother of the West, keeper of the elixir of life.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (18,'jingwei','精卫','Jingwei','yingxiong',22,'炎帝之女，衔石填海。','Yandi''s daughter, reborn to fill the sea with stones.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (19,'xingtian','刑天','Xingtian','shen',24,'断首仍操干戚而舞。','Beheaded titan who still dances with shield and axe.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (20,'yinglong','应龙','Yinglong','shen',24,'有翼之龙，助黄帝杀蚩尤。','Winged dragon who helped Huangdi slay Chiyou.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (21,'xiangliu','相柳','Xiangliu','xiongshen',22,'共工九首之臣，禹所诛。','Gonggong''s nine-headed minister, slain by Yu.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (22,'taiyi','东皇太一','Taiyi','shen',26,'至高天帝，楚地尊神。','Supreme celestial god venerated in the state of Chu.');
INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (23,'qiyu','启','Qi','yingxiong',20,'禹之子，开夏王朝。','Son of Yu; founded the Xia dynasty.');

INSERT INTO graph_links (s,t,r) VALUES ('pangu','nuwa','descend');
INSERT INTO graph_links (s,t,r) VALUES ('nuwa','fuxi','spouse');
INSERT INTO graph_links (s,t,r) VALUES ('fuxi','yandi','ally');
INSERT INTO graph_links (s,t,r) VALUES ('yandi','huangdi','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('huangdi','chiyou','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('huangdi','yinglong','ally');
INSERT INTO graph_links (s,t,r) VALUES ('yinglong','chiyou','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('yinglong','kuafu','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('chiyou','kuafu','ally');
INSERT INTO graph_links (s,t,r) VALUES ('yandi','jingwei','parent');
INSERT INTO graph_links (s,t,r) VALUES ('yandi','zhurong','descend');
INSERT INTO graph_links (s,t,r) VALUES ('zhurong','gonggong','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('gonggong','xiangliu','ally');
INSERT INTO graph_links (s,t,r) VALUES ('huangdi','zhuanxu','parent');
INSERT INTO graph_links (s,t,r) VALUES ('zhuanxu','diku','descend');
INSERT INTO graph_links (s,t,r) VALUES ('diku','yao','parent');
INSERT INTO graph_links (s,t,r) VALUES ('yao','shun','descend');
INSERT INTO graph_links (s,t,r) VALUES ('yao','houyi','ally');
INSERT INTO graph_links (s,t,r) VALUES ('houyi','change','spouse');
INSERT INTO graph_links (s,t,r) VALUES ('shun','gun','ally');
INSERT INTO graph_links (s,t,r) VALUES ('gun','dayu','parent');
INSERT INTO graph_links (s,t,r) VALUES ('dayu','xiangliu','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('dayu','yinglong','ally');
INSERT INTO graph_links (s,t,r) VALUES ('dayu','qiyu','parent');
INSERT INTO graph_links (s,t,r) VALUES ('zhuanxu','gonggong','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('xiwangmu','houyi','ally');
INSERT INTO graph_links (s,t,r) VALUES ('taiyi','huangdi','descend');
INSERT INTO graph_links (s,t,r) VALUES ('xingtian','huangdi','enemy');
INSERT INTO graph_links (s,t,r) VALUES ('fuxi','nuwa','parent');
