/* ============================================================
   Generate migrations/0001_init.sql from the typed TS data.
   Run: node scripts/gen-seed.ts   (Node 24 strips TS types natively)
   ============================================================ */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CREATURES } from "../app/data/creatures.ts";
import { GRAPH_LINKS, GRAPH_NODES } from "../app/data/graph.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "migrations");

const q = (v: string | number) =>
	typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`;
const json = (v: unknown) => q(JSON.stringify(v));

const lines: string[] = [
	"-- AUTO-GENERATED by scripts/gen-seed.ts — do not edit by hand.",
	"-- 华夏神话 schema + seed (public-domain《山海经》data).",
	"",
	"DROP TABLE IF EXISTS creatures;",
	"DROP TABLE IF EXISTS graph_nodes;",
	"DROP TABLE IF EXISTS graph_links;",
	"",
	`CREATE TABLE creatures (
  ord INTEGER NOT NULL,
  id TEXT PRIMARY KEY,
  glyph TEXT NOT NULL, cat TEXT NOT NULL, region TEXT NOT NULL,
  omen TEXT NOT NULL, color TEXT NOT NULL,
  zh TEXT NOT NULL, en TEXT NOT NULL, py TEXT NOT NULL,
  tags_zh TEXT NOT NULL, tags_en TEXT NOT NULL,
  src TEXT NOT NULL, ref TEXT NOT NULL, bai TEXT NOT NULL, en_sum TEXT NOT NULL
);`,
	"CREATE INDEX idx_creatures_cat ON creatures(cat);",
	"CREATE INDEX idx_creatures_region ON creatures(region);",
	"CREATE INDEX idx_creatures_omen ON creatures(omen);",
	"",
	`CREATE TABLE graph_nodes (
  ord INTEGER NOT NULL,
  id TEXT PRIMARY KEY,
  zh TEXT NOT NULL, en TEXT NOT NULL, g TEXT NOT NULL,
  r INTEGER NOT NULL, desc_zh TEXT NOT NULL, desc_en TEXT NOT NULL
);`,
	`CREATE TABLE graph_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  s TEXT NOT NULL, t TEXT NOT NULL, r TEXT NOT NULL
);`,
	"",
];

CREATURES.forEach((c, i) => {
	lines.push(
		`INSERT INTO creatures (ord,id,glyph,cat,region,omen,color,zh,en,py,tags_zh,tags_en,src,ref,bai,en_sum) VALUES (` +
			[
				i,
				q(c.id),
				q(c.glyph),
				q(c.cat),
				q(c.region),
				q(c.omen),
				q(c.color),
				q(c.zh),
				q(c.en),
				q(c.py),
				json(c.tags_zh),
				json(c.tags_en),
				q(c.src),
				q(c.ref),
				q(c.bai),
				q(c.en_sum),
			].join(",") +
			");",
	);
});
lines.push("");

GRAPH_NODES.forEach((n, i) => {
	lines.push(
		`INSERT INTO graph_nodes (ord,id,zh,en,g,r,desc_zh,desc_en) VALUES (` +
			[i, q(n.id), q(n.zh), q(n.en), q(n.g), n.r, q(n.desc_zh), q(n.desc_en)].join(",") +
			");",
	);
});
lines.push("");

GRAPH_LINKS.forEach((l) => {
	lines.push(
		`INSERT INTO graph_links (s,t,r) VALUES (${[q(l.s), q(l.t), q(l.r)].join(",")});`,
	);
});
lines.push("");

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "0001_init.sql"), lines.join("\n"), "utf8");
console.log(
	`wrote migrations/0001_init.sql — ${CREATURES.length} creatures, ${GRAPH_NODES.length} nodes, ${GRAPH_LINKS.length} links`,
);
